version: '2'

services:
  app:
    build: app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/src/app
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
